<?php
/**
 * @var \Phalcon\Mvc\View\Engine $this
 */

echo $this->getContent();
?>

<h1>Edit $plural$</h1>

<div class="col-md-6 col-sm-6">
    <?php echo $this->tag->form(array("$plural$/save", "class" => "form-horizontal")) ?>
        <?php echo $this->tag->linkTo(array("$plural$", "Back")) ?>
        <fieldset>
            <?php echo $this->tag->hiddenField("id") ?>
            $captureFields$
            <div class="form-group">
                <?php echo $this->tag->submitButton(array('Save', 'class' => 'btn btn-success col-sm-offset-4')); ?>
            </div>
        </fieldset>
    </form>
</div>
