<?php
/**
 * @var \Phalcon\Mvc\View\Engine $this
 */

echo $this->getContent();
?>

<h1>Search $plural$</h1>

<div class="col-md-6 col-sm-6">
    <?php echo $this->tag->form(array("$plural$/search", "autocomplete" => "off", "class" => "form-horizontal")) ?>
        <?php echo $this->tag->linkTo(array("$plural$/new", "Create $plural$")) ?>
        <fieldset>
            $captureFields$
            <div class="form-group">
                <?php echo $this->tag->submitButton(array('Search', 'class' => 'btn btn-success col-sm-offset-4')); ?>
            </div>
        </fieldset>
    </form>
</div>