<?php
/**
 * @var \Phalcon\Mvc\View\Engine $this
 */

echo $this->getContent();
?>

<div class="btn-toolbar">
    <?php echo $this->tag->linkTo(array("$plural$/index", "Go Back", "class" => "btn btn-success")); ?>
    <?php echo $this->tag->linkTo(array("$plural$/new", "Create", "class" => "btn btn-success")); ?>
</div>

<div class="panel panel-default">
    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
$headerColumns$
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $singularVar$) { ?>
            <tr>
$rowColumns$
                <td><?php echo $this->tag->linkTo(array("$plural$/edit/" . $singularVar$->$pk$, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("$plural$/delete/" . $singularVar$->$pk$, "Delete")); ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

<nav>
    <ul class="pagination">
        <li><?php echo $this->tag->linkTo("$plural$/search", "First") ?></li>
        <li><?php echo $this->tag->linkTo("$plural$/search?page=" . $page->before, "Previous") ?></li>
        <li><?php echo $this->tag->linkTo("$plural$/search?page=" . $page->next, "Next") ?></li>
        <li><?php echo $this->tag->linkTo("$plural$/search?page=" . $page->last, "Last") ?></li>
    </ul>
</nav>